#!/bin/bash

KEY=.chef/data_bag.key
if test -r "${KEY}" ; then
  echo "Remove key: ${KEY}"
  exit 1
fi

echo "Create data bag key?"
read
openssl rand -base64 512 | \
tr -d '\r\n' > ${KEY}

chmod 600 ${KEY}
